export { escapeHtml } from './html'
export { hreflangTags, type HreflangResult, type HreflangRow } from './hreflang'
export { productJsonLd, type ProductInput, type ProductResult } from './product'
export { robotsTest, type RobotsTestResult } from './robots'
export { arabicSlug, type SlugResult } from './slug'
export { whatsAppLink, type WhatsAppInput, type WhatsAppResult } from './whatsapp'
